app = "wilowilo-api"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "3001"

[deploy]
  release_command = "npx prisma migrate deploy"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = "connections"
    hard_limit = 50
    soft_limit = 40

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
